name: XDiscordUltimate
main: com.xreatlabs.xdiscordultimate.XDiscordUltimate
version: 1.0.0
api-version: 1.16
author: XReatLabs
description: Advanced Discord integration for Minecraft servers
website: https://github.com/xreatlabs/xdiscordultimate
softdepend: [LuckPerms, PlaceholderAPI, Vault]

commands:
  verify:
    description: Link your Discord account with Minecraft
    usage: /<command>
    aliases: [link, discord]
  
  support:
    description: Open a support ticket on Discord
    usage: /<command> <message>
    aliases: [ticket]
  
  help:
    description: Show XDiscordUltimate help GUI
    usage: /<command> [category]
    aliases: [xhelp, xdhelp]
  
  embed:
    description: Send a custom embed to Discord
    usage: /<command> <channel> <title> <description>
    permission: xdiscord.embed
  
  announce:
    description: Broadcast an announcement to Discord and in-game
    usage: /<command> <message>
    permission: xdiscord.announce
  
  discordconsole:
    description: Execute bot console commands
    usage: /<command> <command>
    permission: xdiscord.console
  
  report:
    description: Report a player to Discord moderators
    usage: /<command> <player> <reason>
    aliases: [reportplayer]
  
  msg:
    description: Send a private message to a Discord user
    usage: /<command> <discord_user> <message>
    permission: xdiscord.msg

  statusgraph:
    description: Display a live status graph in Discord
    usage: /<command>
    permission: xdiscord.statusgraph
  
  playtime:
    description: Check your or another player's playtime
    usage: /<command> [player]
    permission: xdiscord.playtime
    aliases: [pt, playtime]
  
  xdiscord:
    description: Main XDiscordUltimate command
    usage: /<command> [reload|status|help|key|network|run]
    permission: xdiscord.admin
    aliases: [xdu, xdiscordultimate]

permissions:
  xdiscord.*:
    description: All XDiscordUltimate permissions
    default: op
    children:
      xdiscord.admin: true
      xdiscord.embed: true
      xdiscord.announce: true
      xdiscord.console: true
      xdiscord.verify: true
      xdiscord.support: true
      xdiscord.report: true
      xdiscord.msg: true
      xdiscord.statusgraph: true
      xdiscord.bypass.verification: true
  
  xdiscord.admin:
    description: Administrative permissions
    default: op
  
  xdiscord.embed:
    description: Send Discord embeds
    default: op
  
  xdiscord.announce:
    description: Make announcements
    default: op
  
  xdiscord.console:
    description: Access Discord bot console
    default: false
  
  xdiscord.verify:
    description: Use verification command
    default: true
  
  xdiscord.support:
    description: Create support tickets
    default: true
  
  xdiscord.report:
    description: Report players
    default: true

  xdiscord.msg:
    description: Send a private message to a Discord user
    default: true

  xdiscord.statusgraph:
    description: Display a live status graph in Discord
    default: op
  
  xdiscord.bypass.verification:
    description: Bypass Discord verification requirement
    default: false
  
  xdiscord.playtime:
    description: Check your own playtime
    default: true
  
  xdiscord.playtime.others:
    description: Check other players' playtime
    default: op